#pragma once

// Centralized persistent storage keys used across the app.
typedef enum PersistKey {
    PERSIST_KEY_SETTINGS = 1,
    PERSIST_KEY_SETTINGS_VERSION = 2,
    PERSIST_KEY_WEATHER_DATA = 3,
    PERSIST_KEY_WEATHER_FORECAST_TEMP_0 = 4,
    PERSIST_KEY_WEATHER_FORECAST_TEMP_1 = 5,
    PERSIST_KEY_WEATHER_FORECAST_RAIN_0 = 6,
    PERSIST_KEY_WEATHER_FORECAST_RAIN_1 = 7,
    PERSIST_KEY_APP_VERSION = 8,
} PersistKey;

