name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: spr4bhu/pebble-actions@v1
        id: pebble
      - run: pebble build
      - run: echo "Built with SDK ${{ steps.pebble.outputs.sdk-version }}"